# This is a config for E2B sandbox template.
# You can use template ID (q1pd5rogdmvgwwa884mc) or template name (vibe-nextjs-test-arvind) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-nextjs-test-arvind") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-arvind") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-arvind')

start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-arvind"
template_id = "q1pd5rogdmvgwwa884mc"
